language: c
sudo: required
dist: focal
os: linux
arch: arm64-graviton2

script:
 - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage && chmod +x appimagetool-x86_64.AppImage
 - mv appimagetool-x86_64.AppImage appimagetool && cp appimagetool /home/travis/bin

 - wget -q https://github.com/mmtrt/WINE_AppImage/releases/download/continuous-testing/wine-stable-x86_64.AppImage
 - wget -q https://github.com/mmtrt/WINE_AppImage/releases/download/continuous-testing/wine-devel-x86_64.AppImage
 - wget -q https://github.com/mmtrt/WINE_AppImage/releases/download/continuous-testing/wine-staging-x86_64.AppImage

 - chmod +x *.AppImage
 - ls -al

 - ./wine-devel-x86_64.AppImage --appimage-extract &>/dev/null
 # Disable winemenubuilder
 - sed -i 's/winemenubuilder.exe -a -r/winemenubuilder.exe -r/g' squashfs-root/opt/wine-devel/share/wine/wine.inf
 # Disable FileOpenAssociations
 - sed -i 's|    LicenseInformation|    LicenseInformation,\\\n    FileOpenAssociations|g;$a \\n[FileOpenAssociations]\nHKCU,Software\\Wine\\FileOpenAssociations,"Enable",,"N"' squashfs-root/opt/wine-devel/share/wine/wine.inf
 - |-
   sed -i -E 's,(^.+"library_path": ")/.*/,\1,' squashfs-root/usr/share/vulkan/icd.d/*intel*.json
   sed -i -E 's,(^.+"library_path": ")/.*/,\1,' squashfs-root/usr/share/vulkan/icd.d/*radeon*.json
 - rm wine-devel-x86_64.AppImage
 - export ARCH=x86_64; appimagetool -v squashfs-root -u 'gh-releases-zsync|mmtrt|WINE_AppImage|continuous-test|wine-devel*.AppImage.zsync' wine-devel-x86_64.AppImage
 - rm -rf squashfs-root

 - ./wine-stable-x86_64.AppImage --appimage-extract &>/dev/null
 # Disable winemenubuilder
 - sed -i 's/winemenubuilder.exe -a -r/winemenubuilder.exe -r/g' squashfs-root/opt/wine-stable/share/wine/wine.inf
 # Disable FileOpenAssociations
 - sed -i 's|    LicenseInformation|    LicenseInformation,\\\n    FileOpenAssociations|g;$a \\n[FileOpenAssociations]\nHKCU,Software\\Wine\\FileOpenAssociations,"Enable",,"N"' squashfs-root/opt/wine-stable/share/wine/wine.inf
 - |-
   sed -i -E 's,(^.+"library_path": ")/.*/,\1,' squashfs-root/usr/share/vulkan/icd.d/*intel*.json
   sed -i -E 's,(^.+"library_path": ")/.*/,\1,' squashfs-root/usr/share/vulkan/icd.d/*radeon*.json
 - rm wine-stable-x86_64.AppImage
 - export ARCH=x86_64; appimagetool -v squashfs-root -u 'gh-releases-zsync|mmtrt|WINE_AppImage|continuous-test|wine-stable*.AppImage.zsync' wine-stable-x86_64.AppImage
 - rm -rf squashfs-root

 - ./wine-staging-x86_64.AppImage --appimage-extract &>/dev/null
 # Disable winemenubuilder
 - sed -i 's/winemenubuilder.exe -a -r/winemenubuilder.exe -r/g' squashfs-root/opt/wine-staging/share/wine/wine.inf
 # Disable FileOpenAssociations
 - sed -i 's|    LicenseInformation|    LicenseInformation,\\\n    FileOpenAssociations|g;$a \\n[FileOpenAssociations]\nHKCU,Software\\Wine\\FileOpenAssociations,"Enable",,"N"' squashfs-root/opt/wine-staging/share/wine/wine.inf
 - |-
   sed -i -E 's,(^.+"library_path": ")/.*/,\1,' squashfs-root/usr/share/vulkan/icd.d/*intel*.json
   sed -i -E 's,(^.+"library_path": ")/.*/,\1,' squashfs-root/usr/share/vulkan/icd.d/*radeon*.json
 - rm wine-staging-x86_64.AppImage
 - export ARCH=x86_64; appimagetool -v squashfs-root -u 'gh-releases-zsync|mmtrt|WINE_AppImage|continuous-test|wine-staging*.AppImage.zsync' wine-staging-x86_64.AppImage
 - rm -rf squashfs-root

 - sha512sum *.AppImage* > SHA512 ; ls -al

env:
  global:
    - RELEASE_BRANCH="master"

after_success:
  # uploadtool
 - wget -c https://raw.githubusercontent.com/probonopd/uploadtool/8142d461aba7b92a058116fe5ee75be438b75fa4/upload.sh
 - |- # publish
   if [[ ("$TRAVIS_BRANCH" != "$RELEASE_BRANCH" && "$TRAVIS_BRANCH" != "$TRAVIS_TAG") || "$TRAVIS_EVENT_TYPE" != "push" ]]; then
     echo 'Publishing release to GitHub...'
     export UPLOADTOOL_SUFFIX="$TRAVIS_BRANCH"
     export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***$UPLOADTOOL_SUFFIX experimental build*** for testing new features.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
     bash upload.sh *.AppImage* SHA512
   elif [[ "$TRAVIS_BRANCH" != "$TRAVIS_TAG" ]]; then
     echo 'Publishing release to GitHub...'
     export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***latest development build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
     bash upload.sh *.AppImage* SHA512
   else
     echo 'Publishing release to GitHub...'
     export UPLOADTOOL_BODY="Instructions on using the AppImage can be found [here](https://github.com/${TRAVIS_REPO_SLUG}/blob/master/README.md)\n\nThis is the ***release $TRAVIS_TAG stable build***.\n\nTravis CI build log: $TRAVIS_BUILD_WEB_URL"
     bash upload.sh *.AppImage* SHA512
   fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^release-[0-9a-z\-]*/
    - /^(?i:untagged)-.*$/
