name: Release
on:
  schedule:
    - cron: "0 * * * */7"
  push:
    branches:
      - "tmp"
  pull_request:
    branches:
      - "tmp"


jobs:
  Stable:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: ['3.8']
    steps:
    - uses: actions/checkout@v2

    - name: Prerequisites
      run: |
        sudo apt-get -y install python3 python3-setuptools python3-pip wget patchelf fakeroot gnupg2 libglib2.0-bin file desktop-file-utils libgdk-pixbuf2.0-dev librsvg2-dev zsync
        mkdir -p /usr/share/icons/hicolor/scalable/ ; cp wine.svg /usr/share/icons/hicolor/scalable/
        pip3 install appimage-builder
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage && chmod +x appimagetool-x86_64.AppImage
        mv appimagetool-x86_64.AppImage appimagetool && cp appimagetool $HOME/bin && ls -al && ls -al $HOME/bin
        wget https://gist.githubusercontent.com/mmtrt/8d1a2b9eb33429feb0197ec46b0acdf4/raw/493a1700897897963dba24ffe2985d6e00a71ba1/nvidia_icd.json
        export PATH=$PATH:"$HOME/.local/bin"

    - name: Build AppImage
      run: |
        appimage-builder --skip-tests --recipe wine-stable.yml
        chmod +x *.AppImage

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: wine-stable-x86_64.AppImage
        path: './'

  Release:
    needs: [Stable]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v1
      with:
        name: wine-stable-x86_64.AppImage

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: WINE Stable AppImage Builds
        automatic_release_tag: stable
        prerelease: true
        draft: false
        files: |
          wine-stable-x86_64.AppImage
        repo_token: ${{ secrets.GITHUB_TOKEN }}
