# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test2 ]
  pull_request:
    branches: [ test2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Stable"
  Stable:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Prerequisites
        run: |
          sudo dpkg --add-architecture i386
          pip3 install appimage-builder
          mkdir -p /usr/share/icons/hicolor/scalable/ ; cp wine.svg /usr/share/icons/hicolor/scalable/
          wget https://gist.githubusercontent.com/mmtrt/8d1a2b9eb33429feb0197ec46b0acdf4/raw/493a1700897897963dba24ffe2985d6e00a71ba1/nvidia_icd.json
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage && chmod +x appimagetool-x86_64.AppImage
          mv appimagetool-x86_64.AppImage appimagetool && sudo mv appimagetool /usr/bin

      # Runs a set of commands using the runners shell
      - name: Build appimage
        run: |
          appimage-builder --skip-tests --recipe wine-stable.yml
          chmod +x *.AppImage
          mkdir dist
          mv wine*.AppImage* dist/.

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: wine-stable-continuous-x86_64.AppImage
          path: 'dist'

  Release-stable:
      needs: [Stable]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: wine-stable-continuous-x86_64.AppImage

        - name: Release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous Builds
            automatic_release_tag: stable
            prerelease: false
            draft: false
            files: |
              wine-stable-continuous-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}