# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test2 ]
  pull_request:
    branches: [ test2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Stable"
  Stable:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Enable i386 arch & update apt
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update -y -qq
          wget -nc https://dl.winehq.org/wine-builds/winehq.key
          sudo apt-key add winehq.key

      # Runs a set of commands using the runners shell
      - name: Build appimage
        uses: AppImageCrafters/build-appimage@master
        with:
          recipe: "./wine-stable.yml"
          args: "--skip-tests"

      - name: Move appimage
        run: |
          chmod +x *.AppImage
          mkdir dist
          mv wine*.AppImage* dist/.

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: wine-stable-continuous-x86_64.AppImage
          path: 'dist'

  Release-stable:
      needs: [Stable]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: wine-stable-continuous-x86_64.AppImage

        - name: Release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous Builds
            automatic_release_tag: stable
            prerelease: false
            draft: false
            files: |
              wine-stable-continuous-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}