# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test2 ]
  pull_request:
    branches: [ test2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prerequisites
        run: |
          VER=$(wget -qO- https://github.com/AppImageCrafters/appimage-builder/releases/tag/Continuous | grep x86_64 | cut -d'"' -f2 | head -1)
          wget https://github.com"${VER}" -O appimage-builder ; chmod +x appimage-builder ; sudo mv appimage-builder /usr/bin
          mkdir -p /usr/share/icons/hicolor/scalable/ ; cp wine.svg /usr/share/icons/hicolor/scalable/
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage && chmod +x appimagetool-x86_64.AppImage
          mv appimagetool-x86_64.AppImage appimagetool && sudo mv appimagetool /usr/bin

      # Runs a set of commands using the runners shell
      - name: Build appimage
        run: |
          # add dir dist
          mkdir dist

          # # stable
          # WINE_VER="$(wget -qO- https://dl.winehq.org/wine-builds/ubuntu/dists/focal/main/binary-amd64/ | grep wine-stable | sed 's|_| |g;s|~| |g' | awk '{print $5}' | tail -n1)"
          # appimage-builder --skip-tests --skip-appimage --recipe wine-stable.yml
          # # Disable FileOpenAssociations
          # sed -i 's|    LicenseInformation|    LicenseInformation,\\\n    FileOpenAssociations|g;$a \\n[FileOpenAssociations]\nHKCU,Software\\Wine\\FileOpenAssociations,"Enable",,"N"' AppDir/opt/wine-stable/share/wine/wine.inf
          # # Disable winemenubuilder
          # sed -i 's|    FileOpenAssociations|    FileOpenAssociations,\\\n    DllOverrides|;$a \\n[DllOverrides]\nHKCU,Software\\Wine\\DllOverrides,"*winemenubuilder.exe",,""' AppDir/opt/wine-stable/share/wine/wine.inf
          # sed -i '/\%11\%\\winemenubuilder.exe -a -r/d' AppDir/opt/wine-stable/share/wine/wine.inf
          # # Pre patching DPI setting DPI dword value 240=f0 180=b4 120=78 110=6e 100=64 96=60
          # sed -i 's|0x00000060|0x00000064|' AppDir/opt/wine-stable/share/wine/wine.inf
          # export ARCH=x86_64; appimagetool -v ./AppDir -u "gh-releases-zsync|mmtrt|WINE_AppImage|continuous|wine-stable*.AppImage.zsync" wine-stable_${WINE_VER}-${ARCH}.AppImage
          # mv *AppImage* dist/.

          # stable-i386
          WINE_VER="$(wget -qO- https://dl.winehq.org/wine-builds/ubuntu/dists/focal/main/binary-amd64/ | grep wine-stable | sed 's|_| |g;s|~| |g' | awk '{print $5}' | tail -n1)"
          appimage-builder --skip-tests --skip-appimage --recipe wine-stable-i386.yml
          # Disable FileOpenAssociations
          sed -i 's|    LicenseInformation|    LicenseInformation,\\\n    FileOpenAssociations|g;$a \\n[FileOpenAssociations]\nHKCU,Software\\Wine\\FileOpenAssociations,"Enable",,"N"' AppDir/opt/wine-stable/share/wine/wine.inf
          # Disable winemenubuilder
          sed -i 's|    FileOpenAssociations|    FileOpenAssociations,\\\n    DllOverrides|;$a \\n[DllOverrides]\nHKCU,Software\\Wine\\DllOverrides,"*winemenubuilder.exe",,""' AppDir/opt/wine-stable/share/wine/wine.inf
          sed -i '/\%11\%\\winemenubuilder.exe -a -r/d' AppDir/opt/wine-stable/share/wine/wine.inf
          # Pre patching DPI setting DPI dword value 240=f0 180=b4 120=78 110=6e 100=64 96=60
          sed -i 's|0x00000060|0x00000064|' AppDir/opt/wine-stable/share/wine/wine.inf
          # Workaround required amd64 pkgs
          # sudo apt install p7zip-full -y
          # wget -q http://archive.ubuntu.com/ubuntu/pool/universe/u/unionfs-fuse/unionfs-fuse_1.0-1ubuntu2_amd64.deb
          # wget -q http://archive.ubuntu.com/ubuntu/pool/universe/m/mesa-demos/mesa-utils_8.4.0-1build1_amd64.deb
          # 7z x unionfs-fuse_1.0-1ubuntu2_amd64.deb -so | 7z x -si -ttar -otmp
          # 7z x mesa-utils_8.4.0-1build1_amd64.deb -so | 7z x -si -ttar -otmp
          # ( rm -rf ./tmp/usr/share ; cd ./tmp/usr/bin ; rm unionfs-fuse ; ln -s unionfs unionfs-fuse )
          # find ./tmp/ -type f -exec chmod +x {} \;
          # cp -Rp ./tmp/usr AppDir/
          # rm ./*.deb ; rm -rf ./tmp
          ( cd ./AppDir/usr/bin ; ln -s ../../opt/wine-stable/bin/* ./ )
          export ARCH=x86_64; appimagetool -v ./AppDir -u "gh-releases-zsync|mmtrt|WINE_AppImage|continuous|wine-stable*.AppImage.zsync" wine-stable-i386_${WINE_VER}-${ARCH}.AppImage
          mv *AppImage* dist/.

          # # devel
          # WINE_VER="$(wget -qO- https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-amd64/ | grep wine-devel | sed 's|_| |g;s|~| |g' | awk '{print $5}' | tail -n1)"
          # appimage-builder --skip-tests --skip-appimage --recipe wine-devel.yml
          # # Disable FileOpenAssociations
          # sed -i 's|    LicenseInformation|    LicenseInformation,\\\n    FileOpenAssociations|g;$a \\n[FileOpenAssociations]\nHKCU,Software\\Wine\\FileOpenAssociations,"Enable",,"N"' AppDir/opt/wine-devel/share/wine/wine.inf
          # # Disable winemenubuilder
          # sed -i 's|    FileOpenAssociations|    FileOpenAssociations,\\\n    DllOverrides|;$a \\n[DllOverrides]\nHKCU,Software\\Wine\\DllOverrides,"*winemenubuilder.exe",,""' AppDir/opt/wine-devel/share/wine/wine.inf
          # sed -i '/\%11\%\\winemenubuilder.exe -a -r/d' AppDir/opt/wine-devel/share/wine/wine.inf
          # # Pre patching DPI setting DPI dword value 240=f0 180=b4 120=78 110=6e 100=64 96=60
          # sed -i 's|0x00000060|0x00000064|' AppDir/opt/wine-devel/share/wine/wine.inf
          # export ARCH=x86_64; appimagetool -v ./AppDir -u "gh-releases-zsync|mmtrt|WINE_AppImage|continuous|wine-devel*.AppImage.zsync" wine-devel_${WINE_VER}-${ARCH}.AppImage
          # mv *AppImage* dist/.

          # # staging
          # WINE_VER="$(wget -qO- https://dl.winehq.org/wine-builds/ubuntu/dists/bionic/main/binary-amd64/ | grep wine-staging | sed 's|_| |g;s|~| |g' | awk '{print $5}' | tail -n1)"
          # appimage-builder --skip-tests --skip-appimage --recipe wine-staging.yml
          # # Disable FileOpenAssociations
          # sed -i 's|    LicenseInformation|    LicenseInformation,\\\n    FileOpenAssociations|g;$a \\n[FileOpenAssociations]\nHKCU,Software\\Wine\\FileOpenAssociations,"Enable",,"N"' AppDir/opt/wine-staging/share/wine/wine.inf
          # # Disable winemenubuilder
          # sed -i 's|    FileOpenAssociations|    FileOpenAssociations,\\\n    DllOverrides|;$a \\n[DllOverrides]\nHKCU,Software\\Wine\\DllOverrides,"*winemenubuilder.exe",,""' AppDir/opt/wine-staging/share/wine/wine.inf
          # sed -i '/\%11\%\\winemenubuilder.exe -a -r/d' AppDir/opt/wine-staging/share/wine/wine.inf
          # # Pre patching DPI setting DPI dword value 240=f0 180=b4 120=78 110=6e 100=64 96=60
          # sed -i 's|0x00000060|0x00000064|' AppDir/opt/wine-staging/share/wine/wine.inf
          # export ARCH=x86_64; appimagetool -v ./AppDir -u "gh-releases-zsync|mmtrt|WINE_AppImage|continuous|wine-staging*.AppImage.zsync" wine-staging_${WINE_VER}-${ARCH}.AppImage
          # mv *AppImage* dist/.

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: wine-continuous-x86_64.AppImage
          path: 'dist'

  release:
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: wine-continuous-x86_64.AppImage

        - name: Release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              wine-continuous-x86_64.AppImage
            repo_token: ${{ secrets.GITHUB_TOKEN }}
